sudo: false
language: c
 
addons:
  apt:
    packages:
    - luarocks
    - pandoc

install: luarocks install --local luacheck

jobs:
  include:
    - if: tag IS blank
      before_script: /home/travis/.luarocks/bin/luacheck . --no-color -q
      script: curl -s https://raw.githubusercontent.com/Aiue/AQT/master/localization_import.sh | bash
    - if: tag IS present
      before_script: /home/travis/.luarocks/bin/luacheck . --no-color -q
      script:
       - curl -s https://raw.githubusercontent.com/Aiue/AQT/master/localization_import.sh | bash
       - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
       - curl -s -H "Content-Type: application/json" -X POST -d "{\"username\": \"Release\", \"content\": \"New release: [AQT-${TRAVIS_TAG}](<https://github.com/Aiue/AQT/releases/tag/${TRAVIS_TAG}>). Get it on [CurseForge](<https://www.curseforge.com/wow/addons/aqt>) or [WoWInterface](<https://www.wowinterface.com/downloads/fileinfo.php?id=25280>)\\\!\"}" $WEBHOOK


after_failure: curl -s https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh | bash -s -- failure $WEBHOOK

branches:
  only:
  - master
  - /^\d+\.\d+\.\d+(\w+)?$/
  - /^\d+\.\d+\.\d+\-(\w+)?$/

notifications:
  email:
    on_success: never
    on_failure: always