sudo: false
language: c
 
addons:
  apt:
    packages:
    - luarocks
    - pandoc

install: luarocks install --local luacheck

jobs:
  include:
    - if: tag IS blank
      script: curl -s https://raw.githubusercontent.com/Aiue/AQT/master/localization_import.sh | bash
    - if: tag IS present
      script:
        - curl -s https://raw.githubusercontent.com/Aiue/AQT/master/localization_import.sh | bash
      	- curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash
 
branches:
  only:
  - master
  - /^\d+\.\d+\.\d+(\w+)?$/
  - /^\d+\.\d+\.\d+\-(\w+)?$/

notifications:
  email:
    on_success: never
    on_failure: always